apiVersion: v1
kind: Service
metadata:
  name: stockbot-db
  namespace: dev
  labels:
    app: stockbot-db
spec:
  type: NodePort
  selector:
    app: stockbot-db
  ports:
    - port: 3306
      targetPort: 3306
