---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockbot-db
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockbot-db
  template:
    metadata:
      labels:
        app: stockbot-db
    spec:
      containers:
        - name: stockbot-db
          image: makwanji/stockbot-db:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
          - name: mysql
            containerPort: 3306
          envFrom:
            - configMapRef:
                name: config-common
            - configMapRef:
                name: config-db
          resources:
            requests:
              memory: "256Mi"
              cpu: ".1"
            limits:
              memory: "1024Mi"
              cpu: "1"

