---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: stockbot-backend:latest
          imagePullPolicy: Always
          env:
          ports:
          - name: http
            containerPort: 8000
          envFrom:
            - configMapRef:
                name: config-common
            - configMapRef:
                name: config-backend
          resources:
            requests:
              memory: "256Mi"
              cpu: ".1"
            limits:
              memory: "1024Mi"
              cpu: "1"

