---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: makwanji/stockbot-frontend:latest
          imagePullPolicy: Always
          env:
          ports:
          - name: http
            containerPort: 3000
          envFrom:
            - configMapRef:
                name: config-common
            - configMapRef:
                name: config-frontend
          resources:
            requests:
              memory: "256Mi"
              cpu: ".1"
            limits:
              memory: "1024Mi"
              cpu: "1"

